# GitHub Sponsors + other funding platforms.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [HJrad]
# ko_fi: your-handle
# buy_me_a_coffee: your-handle
